# Generated by Django 3.1.2 on 2021-02-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
