# Generated by Django 3.1.2 on 2021-02-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210214_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follow',
            new_name='follows',
        ),
    ]
